### PR TITLE
fix: process utils causing incompatibilities for some linux distros

### LINKED ISSUE #18: External script editor doesn't list Neovim
I've installed this plugin from the git url, and it doesn't seem to show anything new in "External Script Editor". Nothing after restarting neither

This is on unity 6000.0.44f1 on NixOS. `nvim` is on PATH

### PR DESCRIPTION
**Pull request by Eddio0141**
Process utils was assuming -c exists for all types of shell. This can cause problems for some shells (such as nushell) as this isn't valid.

Process utils was hiding exceptions, making failures silent.

Process utils now also directly executes the specified command, rather than wrapping it in SHELL / cmd.

ProcessUtils.CmdPath replaces ProcessUtils.CheckCmdExistance, and use the result as full path of the cmd.

Now it should be easier to debug process related issues, which was previously silent. And this will always correctly get nvim path from `which` / `where.exe`

Closes #18

### CODE REVIEW

**Comment by Eddio0141** [comment]
Please test on your Linux distro as well. It should work but I might have forgotten something

Also this isn't tested on Windows, please test and ask if there are problems

File: Editor/NeovimCodeEditor.cs [hunk 1]
```diff
@@ -254,15 +260,23 @@ static NeovimCodeEditor()
...
+        using var p = ProcessUtils.HeadlessProcess();
+        // TODO: remove dependency on bash, grep
+        p.StartInfo.FileName = "bash";
+        p.StartInfo.Arguments = @"
 UUID=activate-window-by-title@lucaswerkmeister.de
 if ! gnome-extensions list | grep --quiet $UUID; then
   busctl --user call org.gnome.Shell.Extensions /org/gnome/Shell/Extensions org.gnome.Shell.Extensions InstallRemoteExtension s $UUID
-fi
-", timeout: 10000))
+fi";
```
Comment (Eddio0141) [inline Editor/NeovimCodeEditor.cs]: Forgot to add -c, might as well as clean it up

File: Editor/NeovimCodeEditor.cs [hunk 2]
```diff
@@ -209,21 +209,27 @@ static NeovimCodeEditor()
       InitConfig();
 
       // initialize the discovered Neovim installations array
+      // TODO: ideally, we just check for nvim on path rather than assuming installation paths
```
Comment (walcht) [inline Editor/NeovimCodeEditor.cs]: the previous code already looked for nvim in PATH before checking the assumed installation paths (see the first entry there in s_DiscoveredNeovimInstallations).

If `File.Exists(p)` failes then it is assumed that what is provided is neovim's executable's name in PATH (nvim for linux, nvim.exe for Windows).

The PATH should always be checked first for nvim then check the potential other candidate paths.

File: Editor/ProcessUtils.cs [hunk 3]
```diff
@@ -26,141 +27,61 @@ public static IntPtr GetWindowHandle(Process p, int processStartupTimeout)
...
+    {
+      p.Start();
+      if (!p.WaitForExit(timeout))
+      {
+        try
         {
           p.Kill();
+        } catch (Exception e)
+        {
+          UnityEngine.Debug.LogError("failed to kill process before timeout assertion error");
```
Comment (walcht) [inline Editor/ProcessUtils.cs]: I think this Error log is better:
`UnityEngine.Debug.LogError($"[neovim.ide] failed to kill process before timeout assertion error. Raison: {e.Message}");`

File: Editor/ProcessUtils.cs [hunk 4]
```diff
@@ -1,5 +1,6 @@
 #pragma warning disable IDE0130
 using System;
+using System.IO;
 using System.Diagnostics;
 using System.Collections.Generic;
```
Comment (walcht) [inline Editor/ProcessUtils.cs]: remove this line - it is not used.

File: Editor/NeovimCodeEditor.cs [hunk 5]
```diff
@@ -661,24 +692,38 @@ public bool OpenProject(string filePath = "", int line = -1, int column = -1)
...
-            string cmd = @"gdbus call --session --dest org.gnome.Shell \
+            using var p = ProcessUtils.HeadlessProcess();
+            p.StartInfo.FileName = "gdbus";
+            p.StartInfo.Arguments = @"call --session --dest org.gnome.Shell \
 --object-path /de/lucaswerkmeister/ActivateWindowByTitle \
 --method de.lucaswerkmeister.ActivateWindowByTitle.activateBySubstring 'nvimunity'";
-            if (!ProcessUtils.RunShellCmd(cmd, timeout: s_Config.ProcessTimeout))
-            {
-              Debug.LogWarning($"[neovim.ide] failed to focus on Neovim server instance titled 'nvimunity'.\n"
+            p.Start();
```
Comment (walcht) [inline Editor/NeovimCodeEditor.cs]: Same as the comment above (this gurantees that the process is killed):
```suggestion
            const string error_msg = "[neovim.ide] failed to focus on Neovim server instance titled 'nvimunity'.\n"
                  + "Did you logout and login of your GNOME session?\n"
                  + "Did you install the 'activate-window-by-title@lucaswerkmeister.de' GNOME extension?\n";
            try
            {
              p.RunWithAssertion(s_Config.ProcessTimeout, 0);
            }
            catch (ExitCodeMismatchException)
            {
              Debug.LogWarning($"{error_msg}Reason: non-zero exit code.");
            }
            catch (TimeoutException)
            {
              Debug.LogWarning($"{error_msg}Exception message: timed out after {s_Config.ProcessTimeout} milliseconds.");
            }
            break;

```

**Comment by walcht** [comment]
I fixed all issues on Windows and it seems to work fine on my two other Linux machines (both Ubuntus).
Could you please pull the changes and test it for the last time before I merge. Thanks :-)
